compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

<<<<<<< HEAD
<<<<<<< HEAD
yarnPath: .yarn/releases/yarn-4.4.1.cjs
=======
yarnPath: .yarn/releases/yarn-4.3.1.cjs
>>>>>>> d692414 (feat: Private (non-public) DAOs will be visible under MyDAO tab, and by people who have the URL/address)
=======
yarnPath: .yarn/releases/yarn-4.4.1.cjs
>>>>>>> 4948328 (feat: Private (non-public) DAOs will be visible under MyDAO tab, and … (#358))
