export const Paths = {
  Home: "/",
  Swap: {
    default: "swap",
  },
  Pools: {
    default: "pools",
    AddLiquidity: "pools/add-liquidity",
    Withdraw: "pools/withdraw",
    CreatePool: "pools/create-pool",
  },
  Governance: {
    absolute: "/governance",
    default: "governance",
    ProposalDetails: "proposal-details",
    CreateNewProposal: "create-new-proposal",
    CreateNewToken: "new-token",
    CreateText: "text",
    CreateTokenTransfer: "token-transfer",
    CreateContractUpgrade: "contract-upgrade",
  },
  DAOs: {
    absolute: "/daos",
    default: "daos",
    Create: "create",
    Dashboard: "dashboard",
    DAODetails: "details",
    type: "type",
    GovernanceToken: "governance-token",
    GovernanceTokenVoting: "governance-token/voting",
    GovernanceTokenReview: "governance-token/review",
    Multisig: "multi-sig",
    MultisigVoting: "multi-sig/voting",
    MultisigReview: "multi-sig/review",
    NFT: "nft",
    NFTVoting: "nft/voting",
    NFTReview: "nft/review",
    TransactionDetails: "transactions",
    Assets: "assets",
    Members: "members",
    Settings: "settings",
    Staking: "staking",
    AddMember: "add-member",
    DeleteMember: "delete-member",
    ReplaceMember: "replace-member",
    ChangeThreshold: "change-threshold",
    DetailsStep: "details",
    ReviewStep: "review",
  },
};
