name: Development:Pull Request CI/CD

on:
 pull_request:
   branches: [develop]

jobs:
  build-test-deploy-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: yarn
      
    - name: Check Format
      run: yarn format
      
    - name: Lint
      run: yarn lint

    - name: Build App & Storybook
      run: | 
        CI=false yarn build
        yarn build:storybook
      
