name: Development:Deploy CI/CD

on: 
 push:
   branches: [develop]

jobs:
  build-test-deploy-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: yarn
      
    - name: Check Format
      run: yarn format
      
    - name: Lint
      run: yarn lint

    - name: Build App and Storybook
      run: | 
        CI=false yarn build
        yarn build:storybook

    - name: Deploy Storybook
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
      
