name: Production:Deploy CI / CD

on: 
 push:
   branches: [main]

jobs:
  build-test-deploy-prod:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: yarn
      
    - name: Check Format
      run: yarn format
      
    - name: Lint
      run: yarn lint

    - name: Build App
      run: | 
        yarn build
      
