name: Production:Deploy CI / CD

on: 
 push:
   branches: [main]

jobs:
  build-test-prod:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: yarn
      
    - name: Check Format
      run: yarn format
      
    - name: Lint
      run: yarn lint

    - name: Build
      run: yarn build
      
